name: Deploy Nexus Inventory

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Set Project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker
        run: gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet

      - name: Build and Push Backend
        run: |
          docker build -t asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/product-repo/product-backend:latest ./backend
          docker push asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/product-repo/product-backend:latest

      - name: Build and Push Frontend
        run: |
          docker build -t asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/product-repo/product-frontend:latest ./frontend
          docker push asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/product-repo/product-frontend:latest

      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_IP }}
          username: aarish_khan
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/product-repo/product-backend:latest
            docker pull asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/product-repo/product-frontend:latest
            
            docker network create product-network || true
            docker rm -f product-backend-prod product-frontend-prod || true
            
            docker run -d --name product-backend-prod \
              --network product-network \
              -p 8081:8081 \
              -e SPRING_DATASOURCE_URL=jdbc:postgresql://product-db-prod:5432/productdb \
              -e SPRING_DATASOURCE_USERNAME=product_user \
              -e SPRING_DATASOURCE_PASSWORD=product_pass \
              asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/product-repo/product-backend:latest
            
            docker run -d --name product-frontend-prod \
              --network product-network \
              -p 80:80 \
              asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/product-repo/product-frontend:latest